module.exports = {
terms_by_type : {
    'Corporation': ['company', 'incorporated', 'corporation', 'corp.', 'corp', 'inc',
       '& co.', '& co', 'inc.', 's.p.a.', 'n.v.', 'a.g.', 'ag', 'aktiengesellschaft', 'nuf', 's.a.', 's.f.',
       'oao', 'co.', 'co'
    ],
    'General Partnership': ['soc.col.', 'stg', 'd.n.o.', 'ltda.', 'v.o.s.', 'a spol.',
       've\xc5\x99. obch. spol.', 'kgaa', 'o.e.', 's.f.', 's.n.c.', 's.a.p.a.', 'j.t.d.',
       'v.o.f.', 'sp.j.', 'og', 'sd', ' i/s', 'ay', 'snc', 'oe', 'bt.', 's.s.', 'mb',
       'ans', 'da', 'o.d.', 'hb', 'pt'
    ],
    'Joint Stock / Unlimited': ['unltd', 'ultd', 'sal', 'unlimited', 'saog', 'saoc', 'aj',
       'yoaj', 'oaj', 'akc. spol.', 'a.s.'
    ],
    'Joint Venture': ['esv', 'gie', 'kv.', 'qk'],
    'Limited': ['pty. ltd.', 'pty ltd', 'ltd', 'l.t.d.', 'bvba', 'd.o.o.', 'ltda', 'gmbh',
       'g.m.b.h', 'kft.', 'kht.', 'zrt.', 'ehf.', 's.a.r.l.', 'd.o.o.e.l.', 's. de r.l.',
       'b.v.', 'tapui', 'sp. z.o.o.', 's.r.l.', 's.l.', 's.l.n.e.', 'ood', 'oy', 'rt.',
       'teo', 'uab', 'scs', 'sprl', 'limited', 'bhd.', 'sdn. bhd.', 'sdn bhd', 'as',
       'lda.', 'tov', 'pp'
    ],
    'Limited Liability Company': ['pllc', 'llc', 'l.l.c.', 'plc.', 'plc', 'hf.', 'oyj',
       'a.e.', 'nyrt.', 'p.l.c.', 'sh.a.', 's.a.', 's.r.l.', 'srl.', 'aat', '3at', 'd.d.',
       's.r.o.', 'spol. s r.o.', 's.m.b.a.', 'smba', 'sarl', 'nv', 'sa', 'aps',
       'a/s', 'p/s', 'sae', 'sasu', 'eurl', 'ae', 'cpt', 'as', 'ab', 'asa', 'ooo', 'dat',
       'vat', 'zat', 'mchj', 'a.d.'
    ],
    'Limited Liability Limited Partnership': ['lllp', 'l.l.l.p.'],
    'Limited Liability Partnership': ['llp', 'l.l.p.', 'sp.p.', 's.c.a.', 's.c.s.'],
    'Limited Partnership': ['gmbh & co. kg', 'gmbh & co. kg', 'lp', 'l.p.', 's.c.s.',
       's.c.p.a', 'comm.v', 'k.d.', 'k.d.a.', 's. en c.', 'e.e.', 's.a.s.', 's. en c.',
       'c.v.', 's.k.a.', 'sp.k.', 's.cra.', 'ky', 'scs', 'kg', 'kd', 'k/s', 'ee', 'secs',
       'kda', 'ks', 'kb','kt'
    ],
    'Mutual Fund': ['sicav'],
    'No Liability': ['nl'],
    'Non-Profit': ['vzw', 'ses.', 'gte.'],
    'Private Company': ['private', 'pte', 'xk'],
    'Professional Corporation': ['p.c.', 'vof', 'snc'],
    'Professional Limited Liability Company': ['pllc', 'p.l.l.c.'],
    'Sole Proprietorship': ['e.u.', 's.p.', 't:mi', 'tmi', 'e.v.', 'e.c.', 'et', 'obrt',
       'fie', 'ij', 'fop', 'xt'
    ]
 },
 terms_by_country: {
    'Albania': ['sh.a.', 'sh.p.k.'],
    'Argentina': ['s.a.', 's.r.l.', 's.c.p.a', 'scpa', 's.c.e i.', 's.e.', 's.g.r',
       'soc.col.'
    ],
    'Australia': ['nl', 'pty. ltd.', 'pty ltd'],
    'Austria': ['e.u.', 'stg', 'gesbr', 'a.g.', 'ag', 'og', 'kg', 'aktiengesellschaft'],
    'Belarus': ['aat', '3at'],
    'Belgium': ['esv', 'vzw', 'vof', 'snc', 'comm.v', 'scs', 'bvba', 'sprl', 'cbva',
       'cvoa', 'sca', 'sep', 'gie'
    ],
    'Bosnia / Herzegovina': ['d.d.', 'a.d.', 'd.n.o.', 'd.o.o.', 'k.v.', 's.p.'],
    'Brazil': ['ltda', 's.a.', 'pllc', 'ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
    'Bulgaria': ['ad', 'adsitz', 'ead', 'et', 'kd', 'kda', 'sd'],
    'Cambodia': ['gp', 'sm pte ltd.', 'pte ltd.', 'plc ltd.', 'peec', 'sp'],
    'Canada': ['gp', 'lp', 'sp'],
    'Chile': ['eirl', 's.a.', 'sgr', 's.g.r.', 'ltda', 's.p.a.', 'sa', 's. en c.',
       'ltda.'
    ],
    'Columbia': ['s.a.', 'e.u.', 's.a.s.', 'suc. de descendants', 'sca'],
    'Croatia': ['d.d.', 'd.o.o.', 'obrt'],
    'Czech Republic': ['a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'v.o.s.', 've\xc5\x99. obch. spol.', 'a spol.', 'k.s.', 'kom. spol.', 'kom. spol.'],
    'Denmark': ['i/s', 'a/s', 'k/s', 'p/s', 'amba', 'a.m.b.a.', 'fmba', 'f.m.b.a.', 'smba',
       's.m.b.a.', 'g/s'
    ],
    'Dominican Republic': ['c. por a.', 'cxa', 's.a.', 's.a.s.', 'srl.', 'eirl.', 'sa',
       'sas'
    ],
    'Ecuador': ['s.a.', 'c.a.', 'sa', 'ep'],
    'Egypt': ['sae'],
    'Estonia': ['fie'],
    'Finland': ['t:mi', 'tmi', 'as oy', 'as.oy', 'ay', 'ky', 'oy', 'oyj', 'ok'],
    'France': ['sicav', 'sarl', 'sogepa', 'ei', 'eurl', 'sasu', 'fcp', 'gie', 'sep', 'snc',
       'scs', 'sca', 'scop', 'sem', 'sas'
    ],
    'Germany': ['gmbh & co. kg', 'gmbh & co. kg', 'e.g.', 'e.v.', 'gbr', 'ohg', 'partg',
       'kgaa', 'gmbh', 'g.m.b.h.', 'ag', 'aktiengesellschaft'
    ],
    'Greece': ['a.e.', 'ae', 'e.e.', 'ee', 'epe', 'e.p.e.', 'mepe', 'm.e.p.e.', 'o.e.',
       'oe', 'ovee', 'o.v.e.e.'
    ],
    'Guatemala': ['s.a.', 'sa'],
    'Haiti': ['sa'],
    'Hong Kong': ['ltd', 'unltd', 'ultd', 'limited'],
    'Hungary': ['e.v.', 'e.c.', 'bt.', 'kft.', 'kht.', 'kkt.', 'k.v.', 'zrt.', 'nyrt',
       'ev', 'ec', 'rt.'
    ],
    'Iceland': ['ehf.', 'hf.', 'ohf.', 's.f.', 'ses.'],
    'India': ['pvt. ltd.', 'ltd.', 'psu', 'pse'],
    'Indonesia': ['ud', 'fa', 'pt'],
    'Ireland': ['cpt', 'teo'],
    'Israel': ['b.m.', 'bm', 'ltd', 'limited'],
    'Italy': ['s.n.c.', 's.a.s.', 's.p.a.', 's.a.p.a.', 's.r.l.', 's.c.r.l.', 's.s.'],
    'Latvia': ['as', 'sia', 'ik', 'ps', 'ks'],
    'Lebanon': ['sal'],
    'Lithuania': ['uab', 'ab', 'ij', 'mb'],
    'Luxemborg': ['s.a.', 's.a.r.l.', 'secs'],
    'Macedonia': ['d.o.o.', 'd.o.o.e.l', 'k.d.a.', 'j.t.d.', 'a.d.', 'k.d.'],
    'Malaysia': ['bhd.', 'sdn. bhd.'],
    'Mexico': ['s.a.', 's. de. r.l.', 's. en c.', 's.a.b.', 's.a.p.i.'],
    'Mongolia': ['xk', 'xxk'],
    'Netherlands': ['v.o.f.', 'c.v.', 'b.v.', 'n.v.'],
    'New Zealand': ['tapui', 'ltd', 'limited'],
    'Nigeria': ['gte.', 'plc', 'ltd.', 'ultd.'],
    'Norway': ['asa', 'as', 'ans', 'ba', 'bl', 'da', 'etat', 'fkf', 'hf', 'iks', 'kf',
       'ks', 'nuf', 'rhf', 'sf'
    ],
    'Oman': ['saog', 'saoc'],
    'Pakistan': ['ltd.', 'pvt. ltd.', 'ltd', 'limited'],
    'Peru': ['sa', 's.a.', 's.a.a.'],
    'Philippines': ['coop.', 'corp.', 'corp', 'ent.', 'inc.', 'inc', 'llc', 'l.l.c.',
       'ltd.'
    ],
    'Poland': ['p.p.', 's.k.a.', 'sp.j.', 'sp.k.', 'sp.p.', 'sp. z.o.o.', 's.c.', 's.a.'],
    'Portugal': ['lda.', 'crl', 's.a.', 's.f.', 'sgps'],
    'Romania': ['s.c.a.', 's.c.s.', 's.n.c.', 's.r.l.', 'o.n.g.', 's.a.'],
    'Russia': ['ooo', 'oao', 'zao', '3ao'],
    'Serbia': ['d.o.o.', 'a.d.', 'k.d.', 'o.d.'],
    'Singapore': ['bhd', 'pte ltd', 'sdn bhd', 'llp', 'l.l.p.', 'ltd.', 'pte'],
    'Slovenia': ['d.d.', 'd.o.o.', 'd.n.o.', 'k.d.', 's.p.'],
    'Slovakia': ['a.s.', 'akc. spol.', 's.r.o.', 'spol. s r.o.', 'k.s.', 'kom. spol.', 'v.o.s.', 'a spol.'],
    'Spain': ['s.a.', 's.a.d.', 's.l.', 's.l.l.', 's.l.n.e.', 's.c.', 's.cra', 's.coop',
       'sal', 'sccl'
    ],
    'Sweden': ['ab', 'hb', 'kb'],
    'Switzerland': ['ab', 'sa', 'gmbh', 'g.m.b.h.', 'sarl', 'sagl'],
    'Turkey': ['koop.'],
    'Ukraine': ['dat', 'fop', 'kt', 'pt', 'tdv', 'tov', 'pp', 'vat', 'zat', 'at'],
    'United Kingdom': ['plc.', 'plc', 'cic', 'cio', 'l.l.p.', 'llp', 'l.p.', 'lp', 'ltd.',
       'ltd', 'limited'
    ],
    'United States of America': ['llc', 'inc.', 'corporation', 'incorporated', 'company',
       'limited', 'corp.', 'inc.', 'inc', 'llp', 'l.l.p.', 'pllc', 'and company',
       '& company', 'inc', 'inc.', 'corp.', 'corp', 'ltd.', 'ltd', '& co.', '& co', 'co.',
       'co', 'lp'
    ],
    'Uzbekistan': ['mchj', 'qmj', 'aj', 'oaj', 'yoaj', 'xk', 'xt', 'ok', 'uk', 'qk']
 },
 countries: {
   "Åland Islands": 1,
   "Albania": 1,
   "Algeria": 1,
   "American Samoa": 1,
   "Andorra": 1,
   "Angola": 1,
   "Anguilla": 1,
   "Antarctica": 1,
   "Antigua and Barbuda": 1,
   "Argentina": 1,
   "Armenia": 1,
   "Aruba": 1,
   "Australia": 1,
   "Austria": 1,
   "Azerbaijan": 1,
   "Bahrain": 1,
   "Bahamas": 1,
   "Bangladesh": 1,
   "Barbados": 1,
   "Belarus": 1,
   "Belgium": 1,
   "Belize": 1,
   "Benin": 1,
   "Bermuda": 1,
   "Bhutan": 1,
   "Bolivia": 1,
   "Bonaire": 1,
   "Bosnia and Herzegovina": 1,
   "Botswana": 1,
   "Bouvet Island": 1,
   "Brazil": 1,
   "British Indian Ocean Territory": 1,
   "Brunei Darussalam": 1,
   "Bulgaria": 1,
   "Burkina Faso": 1,
   "Burundi": 1,
   "Cambodia": 1,
   "Cameroon": 1,
   "Canada": 1,
   "Cape Verde": 1,
   "Cayman Islands": 1,
   "Central African Republic": 1,
   "Chad": 1,
   "Chile": 1,
   "China": 1,
   "Christmas Island": 1,
   "Cocos (Keeling) Islands": 1,
   "Colombia": 1,
   "Comoros": 1,
   "Congo": 1,
   "Democratic Republic of the Congo": 1,
   "Cook Islands": 1,
   "Costa Rica": 1,
   "Côte d'Ivoire": 1,
   "Croatia": 1,
   "Cuba": 1,
   "Curaçao": 1,
   "Cyprus": 1,
   "Czech Republic": 1,
   "Denmark": 1,
   "Djibouti": 1,
   "Dominica": 1,
   "Dominican Republic": 1,
   "Ecuador": 1,
   "Egypt": 1,
   "El Salvador": 1,
   "Equatorial Guinea": 1,
   "Eritrea": 1,
   "Estonia": 1,
   "Ethiopia": 1,
   "Falkland Islands (Malvinas)": 1,
   "Faroe Islands": 1,
   "Fiji": 1,
   "Finland": 1,
   "France": 1,
   "French Guiana": 1,
   "French Polynesia": 1,
   "French Southern Territories": 1,
   "Gabon": 1,
   "Gambia": 1,
   "Georgia": 1,
   "Germany": 1,
   "Ghana": 1,
   "Gibraltar": 1,
   "Greece": 1,
   "Greenland": 1,
   "Grenada": 1,
   "Guadeloupe": 1,
   "Guam": 1,
   "Guatemala": 1,
   "Guernsey": 1,
   "Guinea": 1,
   "Guinea-Bissau": 1,
   "Guyana": 1,
   "Haiti": 1,
   "Heard Island and McDonald Islands": 1,
   "Holy See (Vatican City State)": 1,
   "Honduras": 1,
   "Hong Kong": 1,
   "Hungary": 1,
   "Iceland": 1,
   "India": 1,
   "Indonesia": 1,
   "Iran": 1,
   "Iraq": 1,
   "Ireland": 1,
   "Isle of Man": 1,
   "Israel": 1,
   "Italy": 1,
   "Jamaica": 1,
   "Japan": 1,
   "Jersey": 1,
   "Jordan": 1,
   "Kazakhstan": 1,
   "Kenya": 1,
   "Kiribati": 1,
   "Korea": 1,
   "Republic of Korea": 1,
   "Kuwait": 1,
   "Kyrgyzstan": 1,
   "Lao": 1,
   "Latvia": 1,
   "Lebanon": 1,
   "Lesotho": 1,
   "Liberia": 1,
   "Libya": 1,
   "Liechtenstein": 1,
   "Lithuania": 1,
   "Luxembourg": 1,
   "Macao": 1,
   "Macedonia": 1,
   "Madagascar": 1,
   "Malawi": 1,
   "Malaysia": 1,
   "Maldives": 1,
   "Mali": 1,
   "Malta": 1,
   "Marshall Islands": 1,
   "Martinique": 1,
   "Mauritania": 1,
   "Mauritius": 1,
   "Mayotte": 1,
   "Mexico": 1,
   "Micronesia": 1,
   "Moldova": 1,
   "Monaco": 1,
   "Mongolia": 1,
   "Montenegro": 1,
   "Montserrat": 1,
   "Morocco": 1,
   "Mozambique": 1,
   "Myanmar": 1,
   "Namibia": 1,
   "Nauru": 1,
   "Nepal": 1,
   "Netherlands": 1,
   "New Caledonia": 1,
   "New Zealand": 1,
   "Nicaragua": 1,
   "Niger": 1,
   "Nigeria": 1,
   "Niue": 1,
   "Norfolk Island": 1,
   "Northern Mariana Islands": 1,
   "Norway": 1,
   "Oman": 1,
   "Pakistan": 1,
   "Palau": 1,
   "Palestine": 1,
   "Panama": 1,
   "Papua New Guinea": 1,
   "Paraguay": 1,
   "Peru": 1,
   "Philippines": 1,
   "Pitcairn": 1,
   "Poland": 1,
   "Portugal": 1,
   "Puerto Rico": 1,
   "Qatar": 1,
   "R�union": 1,
   "Romania": 1,
   "Russian Federation": 1,
   "Rwanda": 1,
   "Saint Barth�lemy": 1,
   "Saint Helena": 1,
   "Saint Kitts and Nevis": 1,
   "Saint Lucia": 1,
   "Saint Martin (French part)": 1,
   "Saint Pierre and Miquelon": 1,
   "Saint Vincent and the Grenadines": 1,
   "Samoa": 1,
   "San Marino": 1,
   "Sao Tome and Principe": 1,
   "Saudi Arabia": 1,
   "Senegal": 1,
   "Serbia": 1,
   "Seychelles": 1,
   "Sierra Leone": 1,
   "Singapore": 1,
   "Sint Maarten (Dutch part)": 1,
   "Slovakia": 1,
   "Slovenia": 1,
   "Solomon Islands": 1,
   "Somalia": 1,
   "South Africa": 1,
   "South Georgia and the South Sandwich Islands": 1,
   "South Sudan": 1,
   "Spain": 1,
   "Sri Lanka": 1,
   "Sudan": 1,
   "Suriname": 1,
   "Svalbard and Jan Mayen": 1,
   "Swaziland": 1,
   "Sweden": 1,
   "Switzerland": 1,
   "Syrian Arab Republic": 1,
   "Taiwan": 1,
   "Tajikistan": 1,
   "Tanzania": 1,
   "Thailand": 1,
   "Timor-Leste": 1,
   "Togo": 1,
   "Tokelau": 1,
   "Tonga": 1,
   "Trinidad and Tobago": 1,
   "Tunisia": 1,
   "Turkey": 1,
   "Turkmenistan": 1,
   "Turks and Caicos Islands": 1,
   "Tuvalu": 1,
   "Uganda": 1,
   "Ukraine": 1,
   "United Arab Emirates": 1,
   "United Kingdom": 1,
   "United States": 1,
   "United States Minor Outlying Islands": 1,
   "Uruguay": 1,
   "Uzbekistan": 1,
   "Vanuatu": 1,
   "Venezuela": 1,
   "Viet Nam": 1,
   "Virgin Islands": 1,
   "Wallis and Futuna": 1,
   "Western Sahara": 1,
   "Yemen": 1,
   "Zambia": 1,
   "Zimbabwe": 1,
   "AF": 1,
   "AX": 1,
   "AL": 1,
   "DZ": 1,
   "AS": 1,
   "AD": 1,
   "AO": 1,
   "AI": 1,
   "AQ": 1,
   "AG": 1,
   "AR": 1,
   "AM": 1,
   "AW": 1,
   "AU": 1,
   "AT": 1,
   "AZ": 1,
   "BH": 1,
   "BS": 1,
   "BD": 1,
   "BB": 1,
   "BY": 1,
   "BE": 1,
   "BZ": 1,
   "BJ": 1,
   "BM": 1,
   "BT": 1,
   "BO": 1,
   "BQ": 1,
   "BA": 1,
   "BW": 1,
   "BV": 1,
   "BR": 1,
   "IO": 1,
   "BN": 1,
   "BG": 1,
   "BF": 1,
   "BI": 1,
   "KH": 1,
   "CM": 1,
   "CA": 1,
   "CV": 1,
   "KY": 1,
   "CF": 1,
   "TD": 1,
   "CL": 1,
   "CN": 1,
   "CX": 1,
   "CC": 1,
   "CO": 1,
   "KM": 1,
   "CG": 1,
   "CD": 1,
   "CK": 1,
   "CR": 1,
   "CI": 1,
   "HR": 1,
   "CU": 1,
   "CW": 1,
   "CY": 1,
   "CZ": 1,
   "DK": 1,
   "DJ": 1,
   "DM": 1,
   "DO": 1,
   "EC": 1,
   "EG": 1,
   "SV": 1,
   "GQ": 1,
   "ER": 1,
   "EE": 1,
   "ET": 1,
   "FK": 1,
   "FO": 1,
   "FJ": 1,
   "FI": 1,
   "FR": 1,
   "GF": 1,
   "PF": 1,
   "TF": 1,
   "GA": 1,
   "GM": 1,
   "GE": 1,
   "DE": 1,
   "GH": 1,
   "GI": 1,
   "GR": 1,
   "GL": 1,
   "GD": 1,
   "GP": 1,
   "GU": 1,
   "GT": 1,
   "GG": 1,
   "GN": 1,
   "GW": 1,
   "GY": 1,
   "HT": 1,
   "HM": 1,
   "VA": 1,
   "HN": 1,
   "HK": 1,
   "HU": 1,
   "IS": 1,
   "IN": 1,
   "ID": 1,
   "IR": 1,
   "IQ": 1,
   "IE": 1,
   "IM": 1,
   "IL": 1,
   "IT": 1,
   "JM": 1,
   "JP": 1,
   "JE": 1,
   "JO": 1,
   "KZ": 1,
   "KE": 1,
   "KI": 1,
   "KP": 1,
   "KR": 1,
   "KW": 1,
   "KG": 1,
   "LA": 1,
   "LV": 1,
   "LB": 1,
   "LS": 1,
   "LR": 1,
   "LY": 1,
   "LI": 1,
   "LT": 1,
   "LU": 1,
   "MO": 1,
   "MK": 1,
   "MG": 1,
   "MW": 1,
   "MY": 1,
   "MV": 1,
   "ML": 1,
   "MT": 1,
   "MH": 1,
   "MQ": 1,
   "MR": 1,
   "MU": 1,
   "YT": 1,
   "MX": 1,
   "FM": 1,
   "MD": 1,
   "MC": 1,
   "MN": 1,
   "ME": 1,
   "MS": 1,
   "MA": 1,
   "MZ": 1,
   "MM": 1,
   "NA": 1,
   "NR": 1,
   "NP": 1,
   "NL": 1,
   "NC": 1,
   "NZ": 1,
   "NI": 1,
   "NE": 1,
   "NG": 1,
   "NU": 1,
   "NF": 1,
   "MP": 1,
   "NO": 1,
   "OM": 1,
   "PK": 1,
   "PW": 1,
   "PS": 1,
   "PA": 1,
   "PG": 1,
   "PY": 1,
   "PE": 1,
   "PH": 1,
   "PN": 1,
   "PL": 1,
   "PT": 1,
   "PR": 1,
   "QA": 1,
   "RE": 1,
   "RO": 1,
   "RU": 1,
   "RW": 1,
   "BL": 1,
   "SH": 1,
   "KN": 1,
   "LC": 1,
   "MF": 1,
   "PM": 1,
   "VC": 1,
   "WS": 1,
   "SM": 1,
   "ST": 1,
   "SA": 1,
   "SN": 1,
   "RS": 1,
   "SC": 1,
   "SL": 1,
   "SG": 1,
   "SX": 1,
   "SK": 1,
   "SI": 1,
   "SB": 1,
   "SO": 1,
   "ZA": 1,
   "GS": 1,
   "SS": 1,
   "ES": 1,
   "LK": 1,
   "SD": 1,
   "SR": 1,
   "SJ": 1,
   "SZ": 1,
   "SE": 1,
   "CH": 1,
   "SY": 1,
   "TW": 1,
   "TJ": 1,
   "TZ": 1,
   "TH": 1,
   "TL": 1,
   "TG": 1,
   "TK": 1,
   "TO": 1,
   "TT": 1,
   "TN": 1,
   "TR": 1,
   "TM": 1,
   "TC": 1,
   "TV": 1,
   "UG": 1,
   "UA": 1,
   "AE": 1,
   "GB": 1,
   "US": 1,
   "UM": 1,
   "UY": 1,
   "UZ": 1,
   "VU": 1,
   "VE": 1,
   "VN": 1,
   "VG": 1,
   "VI": 1,
   "WF": 1,
   "EH": 1,
   "YE": 1,
   "ZM": 1,
   "ZW": {}
   }
}